name: mate_app
description: "Mate flutter client project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  video_player_media_kit: ^1.0.5
  
  dio: ^4.0.0
  dio_http_cache_lts: ^0.4.1
  dio_smart_retry: ^1.4.0
  
  path_provider: ^2.0.14
  
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  
  logger:
    git:
      url: https://github.com/Bungeefan/logger.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

