name: mate_app
description: "Mate flutter client project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.13+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_highlight: ^0.7.0
  flutter_bloc: ^8.1.2
  path_provider: ^2.0.14
  dart_openai:
    git:
      url: https://github.com/mylxsw/openai.git
  uuid: ^3.0.7
  settings_ui: ^2.0.2
  clipboard: ^0.1.3
  bot_toast: ^4.0.3
  loading_animation_widget: ^1.2.0+4
  flip_card: ^0.7.0
  flutter_slidable: ^2.0.0
  provider: ^6.0.5
  flutter_iconpicker:
    git:
      url: https://github.com/mylxsw/FlutterIconPicker
      ref: hotfix
  share_plus: ^7.2.1
  go_router: ^8.2.0
  sqflite: ^2.2.6
  file_picker: ^5.2.8
  http: ^1.1.0
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  flutter_image_compress: ^1.1.3
  isolate_image_compress: ^2.0.0
  image: ^4.0.15
  flutter_cache_manager: ^3.3.0
  file_saver: ^0.2.9
  image_gallery_saver: ^2.0.0
  tiktoken: ^1.0.3
  flutter_colorpicker: ^1.0.3
  singleton: ^0.0.2
  url_launcher: ^6.1.10
  crypto: ^3.0.2
  dio: ^4.0.0
  dio_http_cache_lts: ^0.4.1
  dio_smart_retry: ^1.4.0
  qiniu_flutter_sdk: ^0.4.0
  sign_in_with_apple: ^4.3.0
  record: ^5.0.4
  animations: ^2.0.7
  animated_text_kit: ^4.2.2
  flutter_localization: ^0.1.11
  random_avatar: ^0.0.8
  in_app_purchase: ^3.1.7
  fluwx: ^3.13.1
  quickalert:
    git:
      url: https://github.com/mylxsw/QuickAlert.git
      ref: master
  sign_in_button: ^3.2.0
  animated_button_bar: ^1.0.0
  circular_countdown_timer: ^0.2.3
  sizer: ^2.0.15
  logger:
    git:
      url: https://github.com/Bungeefan/logger.git
  before_after:
    git:
      url: https://github.com/mylxsw/before_after.git
  flutter_native_splash: ^2.2.19
  flutter_local_notifications: ^14.1.1
  flutter_drawing_board: ^0.4.4+2
  loading_more_list: ^5.0.3
  tobias: ^3.0.0
  flutter_sticky_header: ^0.6.5
  audioplayers: ^5.0.0
  flutter_tts: ^3.7.0
  widgets_to_image: ^0.0.2
  custom_sliding_segmented_control: ^1.7.5
  sqflite_common_ffi: ^2.2.5
  sqflite_common_ffi_web: ^0.4.0
  flutter_markdown: ^0.6.17+3
  markdown: ^7.1.1
  fetch_api: 1.0.1
  web_socket_channel: ^2.4.0
  flutter_initicon: ^3.0.0+1
  markdown_widget: ^2.3.1
  flutter_math_fork: ^0.7.2
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  path: ^1.8.3
  autoscale_tabbarview: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/app.png"
  
  macos:
    generate: true
  web:
    generate: true
  windows:
    generate: true
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: '#FFFFFF'

flutter:


  uses-material-design: true
  
  assets:
    - assets/app.png
    - assets/image-broken.png
    - assets/wechat.png
    - assets/friendroom.png
    - assets/share.png
    - assets/app-256-transparent.png
    - assets/light-dark-auto.png
    - assets/openai.png
    - assets/background.png
    - assets/background-dark.png
    - assets/background-team.png
    - assets/background-team-dark.png
    - assets/background-creative-island.webp
    - assets/background-creative-island-dark.webp
    - assets/background-discovery.png
    - assets/background-discovery-dark.webp
    - assets/transport.png
    - assets/weibo.png
    - assets/github.png
    - assets/x.png
    - assets/xiaohongshu.png
    - assets/play.png
    - assets/text-to-video.gif

tobias:
  url_scheme: tobiasexample
  ios:
    ignore_security: true